name: learning-project-workflow

on:
  push:
    branches:
      - "main"

jobs:
  CI-CD:
    runs-on: "self-hosted"
    steps:
      - name: update system
        run: sudo apt update

      - name: Code-Checkout
        uses: actions/checkout@v4

      - name: Remove Docker Container
        run: |
          docker stop learning-project || true
          docker rm -f learning-project || true

      - name: Build Docker Image
        run: docker build -t learning-project:latest .

      - name: Run Docker Container
        run: |
          docker run -d \
            --name learning-project \
            -p 8000:8000 \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            -e OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
            --restart unless-stopped \
            learning-project:latest

      - name: Docker Clean
        run: docker system prune -af
